name: CI and Release

on:
  push:
    branches:
      - main
    tags:
      - "*" # Push events to every tag not containing /
  pull_request:

jobs:
  hadolint:
    uses: SkynetLabs/.github/.github/workflows/reusable_dockerfile_lint.yml@master

  docker:
    # if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo {{ github }}
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: skynetlabs/blocker:latest,skynetlabs/blocker:latest
